//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_TyryshkinAD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamContent
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int PlayerId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Role Role { get; set; }
        public virtual Team Team { get; set; }
    }
}
