//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_TyryshkinAD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Match = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime StartTimestamp { get; set; }
        public Nullable<System.DateTime> EndTimestamp { get; set; }
        public int FormatId { get; set; }
        public int PrizePool { get; set; }
        public int GameId { get; set; }
        public int ModeratorId { get; set; }
    
        public virtual Format Format { get; set; }
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Match { get; set; }
        public virtual Moderator Moderator { get; set; }
    }
}
